<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="Dell-i37-9Z1F2P2-w11x64" failures="2" tests="2" name="Test(failed)(failed)(failed)" time="0.002" errors="0" timestamp="2025-06-04T15:57:10 IST">
  <testcase classname="ReRun4_Failed_TCs_using_TestNgFailedXMLfile.S1_ClassA" name="testCase1" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at ReRun4_Failed_TCs_using_TestNgFailedXMLfile.S1_ClassA.testCase1(S1_ClassA.java:10)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at ReRun4_Failed_TCs_using_TestNgFailedXMLfile.S3_RunnerFileToExecuteFailedTCsThroughScript.runFailTestCases(S3_RunnerFileToExecuteFailedTCsThroughScript.java:17)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 51 stack frames]]>
    </failure>
  </testcase> <!-- testCase1 -->
  <testcase classname="ReRun4_Failed_TCs_using_TestNgFailedXMLfile.S2_ClassB" name="testCase4" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at ReRun4_Failed_TCs_using_TestNgFailedXMLfile.S2_ClassB.testCase4(S2_ClassB.java:17)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at ReRun4_Failed_TCs_using_TestNgFailedXMLfile.S3_RunnerFileToExecuteFailedTCsThroughScript.runFailTestCases(S3_RunnerFileToExecuteFailedTCsThroughScript.java:17)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 51 stack frames]]>
    </failure>
  </testcase> <!-- testCase4 -->
  <testcase classname="ReRun4_Failed_TCs_using_TestNgFailedXMLfile.S1_ClassA" name="testCase2" time="0.0">
    <ignored/>
  </testcase> <!-- testCase2 -->
  <testcase classname="ReRun4_Failed_TCs_using_TestNgFailedXMLfile.S2_ClassB" name="testCase3" time="0.0">
    <ignored/>
  </testcase> <!-- testCase3 -->
</testsuite> <!-- Test(failed)(failed)(failed) -->
