<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-06-03T18:36:25 IST" name="Default suite" finished-at="2025-06-03T18:36:48 IST" duration-ms="23222">
    <groups>
    </groups>
    <test started-at="2025-06-03T18:36:25 IST" name="Default test" finished-at="2025-06-03T18:36:48 IST" duration-ms="23222">
      <class name="TakesScreenshot_wh_AssertFunction_Fails_Automatically.S2_TestClass">
        <test-method is-config="true" signature="setUp()[pri:0, instance:TakesScreenshot_wh_AssertFunction_Fails_Automatically.S2_TestClass@4d5650ae]" started-at="2025-06-03T18:36:25 IST" name="setUp" finished-at="2025-06-03T18:36:31 IST" duration-ms="6108" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testCase1()[pri:0, instance:TakesScreenshot_wh_AssertFunction_Fails_Automatically.S2_TestClass@4d5650ae]" started-at="2025-06-03T18:36:31 IST" name="testCase1" finished-at="2025-06-03T18:36:35 IST" duration-ms="4303" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at TakesScreenshot_wh_AssertFunction_Fails_Automatically.S2_TestClass.testCase1(S2_TestClass.java:26)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase1 -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:TakesScreenshot_wh_AssertFunction_Fails_Automatically.S2_TestClass@4d5650ae]" started-at="2025-06-03T18:36:35 IST" name="tearDown" finished-at="2025-06-03T18:36:39 IST" duration-ms="4464" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testCase1 status=FAILURE method=S2_TestClass.testCase1()[pri:0, instance:TakesScreenshot_wh_AssertFunction_Fails_Automatically.S2_TestClass@4d5650ae] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:TakesScreenshot_wh_AssertFunction_Fails_Automatically.S2_TestClass@4d5650ae]" started-at="2025-06-03T18:36:39 IST" name="setUp" finished-at="2025-06-03T18:36:47 IST" duration-ms="7809" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testCase2()[pri:0, instance:TakesScreenshot_wh_AssertFunction_Fails_Automatically.S2_TestClass@4d5650ae]" started-at="2025-06-03T18:36:47 IST" name="testCase2" finished-at="2025-06-03T18:36:47 IST" duration-ms="9" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase2 -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:TakesScreenshot_wh_AssertFunction_Fails_Automatically.S2_TestClass@4d5650ae]" started-at="2025-06-03T18:36:47 IST" name="tearDown" finished-at="2025-06-03T18:36:48 IST" duration-ms="406" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testCase2 status=SUCCESS method=S2_TestClass.testCase2()[pri:0, instance:TakesScreenshot_wh_AssertFunction_Fails_Automatically.S2_TestClass@4d5650ae] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- TakesScreenshot_wh_AssertFunction_Fails_Automatically.S2_TestClass -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
